-- V11: 배송지
--
-- 결제에 배송지가 없으면 물건이 어디로 가는지 알 수 없다. 실제 커머스의 주문서에서
-- 가장 먼저 채우는 칸이기도 하다. (D34)
--
-- ── 왜 주문이 아니라 고객에 붙이는가 ──
--
-- 이 프로젝트에는 주문(Order) 엔티티가 없다. 명세는 OrderItem만 두고
-- 같은 상품을 재주문하면 새 행이 아니라 수량을 누적한다(529p).
-- 즉 "한 번의 주문"이라는 단위가 존재하지 않아 거기에 배송지를 걸 자리가 없다.
--
-- 그래서 고객의 배송지로 둔다. 실제 쇼핑몰의 "기본 배송지"에 해당한다.
-- 주문마다 다른 주소로 보내려면 주문 엔티티를 먼저 만들어야 하고,
-- 그건 명세의 모델을 바꾸는 일이라 하지 않았다.

CREATE TABLE delivery_address (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customer_id   VARCHAR(50)  NOT NULL,

    -- 받는 사람. 주문자와 다를 수 있다(선물 등).
    recipient     VARCHAR(50)  NOT NULL,

    -- 연락처. 배송 기사가 쓴다.
    phone         VARCHAR(20)  NOT NULL,

    -- 우편번호. 주소 검색 결과에서 받는다.
    zipcode       VARCHAR(10)  NOT NULL,

    -- 도로명 주소. 검색으로 채워지는 값이라 사용자가 직접 고치지 않는다.
    address       VARCHAR(200) NOT NULL,

    -- 상세 주소. 동·호수처럼 검색으로는 알 수 없는 부분이라 직접 입력한다.
    address_detail VARCHAR(100),

    -- 기본 배송지 여부. 여러 개를 등록해도 결제 화면에는 이것이 먼저 뜬다.
    is_default    BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_delivery_address_customer
        FOREIGN KEY (customer_id) REFERENCES customer (customer_id)
);

-- 고객별 조회가 전부다. 다른 조회 패턴이 없어 인덱스도 이것 하나면 된다.
CREATE INDEX idx_delivery_address_customer ON delivery_address (customer_id);
