-- V16: 결제 원장과 시각 컬럼
--
-- ══════════════ 왜 필요한가 ══════════════
--
-- 카드 승인을 받아놓고 그 기록을 아무 데도 남기지 않고 있었다. (D41)
-- 승인번호는 응답에만 담기고 버려진다. 그러면 이런 것들이 불가능하다.
--
--   - 환불할 때 원거래를 지정할 수 없다 (카드사는 승인번호로 취소를 받는다)
--   - "이 주문 얼마 결제됐죠?"에 답할 수 없다
--   - 카드사 명세서와 대사(對賬)할 수 없다
--
-- 실제 서비스라면 사고다. 결제 원장은 커머스에서 가장 먼저 만드는 테이블이다.
--
-- ══════════════ 한계: 주문 엔티티가 없다 ══════════════
--
-- 명세는 OrderItem만 두고 (고객, 상품) 유니크로 수량을 누적한다(529p).
-- 그래서 **"한 번의 주문"이라는 단위가 존재하지 않는다.**
--
-- 결제 원장을 주문에 걸 수 없으므로 고객에 걸고, 무엇을 샀는지는 별도 컬럼에 요약해 둔다.
-- 정석은 order(주문) → order_line(항목) → payment(결제)로 나누는 것이지만,
-- 그러려면 명세의 모델을 갈아엎어야 해서 하지 않았다.

CREATE TABLE payment (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customer_id      VARCHAR(50)  NOT NULL,

    -- 결제 총액과 그 구성. 셋의 관계는 total = point + card 다.
    total_amount     BIGINT       NOT NULL,
    point_amount     BIGINT       NOT NULL,
    card_amount      BIGINT       NOT NULL,

    -- 이 결제로 적립된 금액. 취소할 때 얼마를 회수할지 알려면 남겨야 한다.
    earned_point     BIGINT       NOT NULL DEFAULT 0,

    -- 카드사 승인번호. 취소할 때 이 번호로 원거래를 지정한다.
    -- 포인트 전액 결제면 카드사를 부르지 않았으므로 NULL이다.
    approval_number  VARCHAR(40),

    -- 마스킹된 카드번호. 사용자가 어느 카드로 냈는지 확인하는 용도다.
    -- 평문 카드번호는 저장하지 않는다. (D32)
    masked_card      VARCHAR(30),

    -- POINT | CARD
    method           VARCHAR(20)  NOT NULL,

    -- PAID | CANCELLED
    status           VARCHAR(20)  NOT NULL,

    -- 무엇을 샀는지 요약. 주문 엔티티가 없어 항목을 걸 자리가 없다.
    -- "세라마이드 수분 크림 외 2건" 같은 문자열이다.
    summary          VARCHAR(200) NOT NULL,

    paid_at          TIMESTAMP    NOT NULL,
    cancelled_at     TIMESTAMP,

    CONSTRAINT fk_payment_customer
        FOREIGN KEY (customer_id) REFERENCES customer (customer_id),

    -- 금액은 음수가 될 수 없고, 구성 합이 총액과 맞아야 한다.
    -- 맞지 않으면 어딘가에서 계산이 어긋난 것이므로 저장 자체를 막는다.
    CONSTRAINT ck_payment_amounts
        CHECK (total_amount >= 0 AND point_amount >= 0 AND card_amount >= 0
               AND total_amount = point_amount + card_amount)
);

-- 고객의 결제 내역 조회가 기본 동선이다. 최신순으로 본다.
CREATE INDEX idx_payment_customer ON payment (customer_id, paid_at DESC);

-- 승인번호로 원거래를 찾는다. 카드사 대사에 쓴다.
CREATE INDEX idx_payment_approval ON payment (approval_number);


-- ══════════════ 시각 컬럼 ══════════════
--
-- 어느 테이블에도 생성 시각이 없었다. "언제 가입했나", "언제 주문했나"에
-- 답할 수 없는 상태였다. 로그를 뒤지는 것 말고는 방법이 없다.
--
-- DEFAULT CURRENT_TIMESTAMP를 준다. 기존 행은 마이그레이션 시각으로 채워지는데,
-- 실제 생성 시각과 다르다. 그 사실을 알고 쓰라는 뜻에서 주석으로 남긴다.
ALTER TABLE customer   ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE order_item ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE order_item ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
