-- V18: 주문 원장
--
-- ══════════════ 왜 뒤늦게 만드는가 ══════════════
--
-- 명세(541p)가 OrderItem만 정의했다는 이유로 주문 엔티티를 만들지 않았다. (D43)
-- 그 결과 이런 것들이 불가능했다.
--
--   - 언제 주문했는지 모른다
--   - 취소하면 흔적이 사라진다 (주문 내역이 "구매 이력"이 아니라 "현재 보유 목록")
--   - 주문 시점의 가격·배송지를 모른다
--   - 결제 원장을 걸 자리가 없다
--
-- 명세를 핑계로 넘어간 것이다. **명세의 모델을 건드리지 않고도 덧붙일 수 있었다.**
--
-- ══════════════ 어떻게 공존하는가 ══════════════
--
--   order_item   명세의 모델. (고객, 상품) 유니크로 **현재 보유 수량**을 누적한다.
--                GET /api/customers/{id}가 반환하는 것이 이것이다. 그대로 둔다.
--
--   orders       **일어난 일**의 기록. 한 번의 결제가 한 행이다. 절대 수정하지 않는다.
--   order_line   그 주문에 담긴 상품들. 주문 시점의 이름과 가격을 복사해 둔다.
--
-- 둘은 목적이 다르다. 전자는 "지금 무엇을 갖고 있나", 후자는 "무슨 일이 있었나"다.
-- 하나로 합치려 하면 둘 중 하나를 잃는다.

CREATE TABLE orders (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 사람이 읽고 부를 수 있는 번호. 고객센터에서 "주문번호 알려주세요"에 쓴다.
    -- id를 그대로 노출하면 전체 주문 수가 드러나고 남의 주문을 추측할 수 있다.
    order_no       VARCHAR(30)  NOT NULL,

    customer_id    VARCHAR(50)  NOT NULL,

    -- PAID | PARTIALLY_CANCELLED | CANCELLED
    status         VARCHAR(24)  NOT NULL,

    total_amount   BIGINT       NOT NULL,
    point_amount   BIGINT       NOT NULL,
    card_amount    BIGINT       NOT NULL,
    earned_point   BIGINT       NOT NULL DEFAULT 0,

    -- ── 배송지 스냅샷 ──
    --
    -- delivery_address를 참조하지 않고 값을 복사한다.
    -- 참조만 두면 나중에 사용자가 이사해서 주소를 고쳤을 때
    -- **과거 주문이 새 주소로 배송된 것처럼 보인다.**
    -- 주문 시점에 어디로 보냈는지는 바뀌면 안 되는 사실이다.
    recipient      VARCHAR(50),
    phone          VARCHAR(20),
    zipcode        VARCHAR(10),
    address        VARCHAR(200),
    address_detail VARCHAR(100),

    ordered_at     TIMESTAMP    NOT NULL,
    cancelled_at   TIMESTAMP,

    CONSTRAINT uk_orders_no UNIQUE (order_no),
    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id) REFERENCES customer (customer_id),
    CONSTRAINT ck_orders_amounts
        CHECK (total_amount >= 0 AND point_amount >= 0 AND card_amount >= 0
               AND total_amount = point_amount + card_amount)
);

CREATE INDEX idx_orders_customer ON orders (customer_id, ordered_at DESC);

CREATE TABLE order_line (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id           BIGINT       NOT NULL,
    product_id         BIGINT       NOT NULL,

    -- 주문 시점의 이름과 단가를 복사한다.
    -- 상품명이 바뀌거나 상품이 삭제돼도 **영수증은 그대로 남아야 한다.**
    product_name       VARCHAR(100) NOT NULL,
    unit_price         BIGINT       NOT NULL,

    quantity           INTEGER      NOT NULL,
    line_amount        BIGINT       NOT NULL,
    used_point         BIGINT       NOT NULL DEFAULT 0,

    -- 이 항목에서 취소된 수량. 부분 취소를 기록한다.
    cancelled_quantity INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT fk_order_line_order
        FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT ck_order_line_quantity
        CHECK (quantity > 0 AND cancelled_quantity >= 0 AND cancelled_quantity <= quantity),
    CONSTRAINT ck_order_line_amount
        CHECK (line_amount >= 0 AND used_point >= 0 AND used_point <= line_amount)
);

CREATE INDEX idx_order_line_order ON order_line (order_id);

-- 결제를 주문에 건다. 이제 "이 주문이 어떻게 결제됐나"에 답할 수 있다.
-- NULL을 허용하는 이유: V16으로 이미 만들어진 결제 행이 있을 수 있다.
ALTER TABLE payment ADD COLUMN order_id BIGINT;
ALTER TABLE payment ADD CONSTRAINT fk_payment_order
    FOREIGN KEY (order_id) REFERENCES orders (id);
