-- V1: 최초 스키마
--
-- 이 파일이 스키마의 유일한 진실 소스다. 엔티티를 고치면 새 마이그레이션을 추가하고,
-- 이 파일은 절대 수정하지 않는다. Flyway가 파일 내용의 체크섬을 저장해 두기 때문에
-- 이미 적용된 마이그레이션을 고치면 다음 기동에서 검증에 실패한다.
--
-- H2(MODE=PostgreSQL)와 PostgreSQL 양쪽에서 동작하는 문법만 쓴다.
-- GENERATED BY DEFAULT AS IDENTITY는 PostgreSQL 10+ 표준이고 H2도 지원한다.
-- SERIAL은 PostgreSQL 전용이라 쓰지 않는다.

CREATE TABLE product (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 컬럼명은 과제 명세(540p)를 따른다. 자바 필드는 name/price다. (D12)
    product_name  VARCHAR(100) NOT NULL,
    -- 금액은 원 단위 정수. Double을 쓰지 않는 이유는 D1에 있다.
    product_price BIGINT       NOT NULL,
    -- 상품명 중복을 DB에서 막는다. 애플리케이션 검사는 좋은 메시지를 위한 것이고
    -- 검사와 저장 사이에 다른 요청이 끼어들 수 있어 최종 방어선은 여기다.
    CONSTRAINT uk_product_name UNIQUE (product_name)
);

CREATE TABLE customer (
    -- 기본 키가 자동 증가 숫자가 아니라 사용자가 정한 로그인 아이디다. 명세 541p를 따른다.
    customer_id       VARCHAR(50)  PRIMARY KEY,
    -- BCrypt 해시는 60자다. 알고리즘이 바뀌어도 견디도록 100으로 잡았다. (D5)
    customer_password VARCHAR(100) NOT NULL,
    customer_point    BIGINT       NOT NULL
);

CREATE TABLE order_item (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  VARCHAR(50) NOT NULL,
    product_id   BIGINT      NOT NULL,
    quantity     INTEGER     NOT NULL,
    -- 단가 스냅샷이 아니라 실제로 결제한 누적 총액이다. 단가를 저장하면 가격 변동 후
    -- 재주문할 때 차감액과 환급액이 어긋나 금전 손실이 생긴다. (D15)
    total_amount BIGINT      NOT NULL,

    CONSTRAINT fk_order_item_customer
        FOREIGN KEY (customer_id) REFERENCES customer (customer_id),
    CONSTRAINT fk_order_item_product
        FOREIGN KEY (product_id) REFERENCES product (id),

    -- 같은 상품을 재주문하면 새 행이 아니라 수량이 누적된다(명세 529p).
    -- 애플리케이션에서만 막으면 동시 요청 둘이 각자 "없음"을 확인하고 행을 두 개 만든다.
    CONSTRAINT uk_order_item_customer_product UNIQUE (customer_id, product_id)
);

-- 조회 패턴에 맞춘 인덱스.
-- 고객의 주문 목록 조회(findByCustomer_CustomerId)가 가장 빈번하다.
-- 유니크 제약이 (customer_id, product_id) 순서라 customer_id 단독 조회도 그 인덱스를 탄다.
-- 상품 삭제 시 참조 검사에는 product_id 인덱스가 필요하다.
CREATE INDEX idx_order_item_product ON order_item (product_id);
