-- V6: 선착순 이벤트
--
-- 한정 수량 하나에 수천 건이 몰리는, 이 프로젝트에서 가장 극단적인 경합 지점이다. (D23)
--
-- P4-A의 재고는 상품마다 행이 나뉘어 있어 경합이 여러 행으로 흩어진다.
-- 선착순 이벤트는 그렇지 않다. 모두가 정확히 같은 하나의 행을 노린다.
-- 락 전략의 차이가 가장 뚜렷하게 드러나는 조건이다.

CREATE TABLE flash_sale (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sale_name       VARCHAR(100) NOT NULL,

    -- 어떤 상품을 파는 이벤트인가. 상품 재고와는 별개로 관리한다.
    -- 이벤트 수량이 상품 재고보다 적은 것이 보통이고, 둘을 한 컬럼으로 합치면
    -- "이벤트가 끝나도 일반 판매는 계속된다"를 표현할 수 없다.
    product_id      BIGINT       NOT NULL,

    -- 처음 걸어둔 수량. 남은 수량과 비교해 몇 개 팔렸는지 계산한다.
    total_quantity  INTEGER      NOT NULL,

    -- 남은 수량. 경합의 대상이 되는 바로 그 값이다.
    remaining       INTEGER      NOT NULL,

    -- 낙관적 락 버전. 네 전략 중 낙관적 락 방식이 이 컬럼을 쓴다.
    -- 다른 전략을 쓸 때도 컬럼은 남아 있지만 Hibernate가 값만 올린다.
    version         BIGINT       NOT NULL DEFAULT 0,

    starts_at       TIMESTAMP    NOT NULL,
    ends_at         TIMESTAMP    NOT NULL,

    CONSTRAINT fk_flash_sale_product
        FOREIGN KEY (product_id) REFERENCES product (id),

    -- 남은 수량은 음수가 될 수 없다. 네 전략 모두 애플리케이션에서 먼저 검사하지만,
    -- 한 전략이라도 검사가 새면 초과 판매가 조용히 성립한다. 최종 방어선을 DB에 둔다.
    CONSTRAINT ck_flash_sale_remaining CHECK (remaining >= 0),

    -- 남은 수량이 처음 수량을 넘을 수 없다. 취소 보상이 잘못 돌면 여기서 걸린다.
    CONSTRAINT ck_flash_sale_remaining_le_total CHECK (remaining <= total_quantity),

    CONSTRAINT ck_flash_sale_period CHECK (ends_at > starts_at)
);

-- 진행 중인 이벤트를 찾는 조회에 쓴다.
CREATE INDEX idx_flash_sale_period ON flash_sale (starts_at, ends_at);
